[SERVICE]
    Flush         5
    Log_Level     info
    Parsers_File  parsers.conf

[INPUT]
    Name              forward
    Listen            0.0.0.0
    Port              24224

[FILTER]
    Name              modify
    Match             *
    Add               service_name sample-api
    Add               environment dev

[OUTPUT]
    Name              cloudwatch_logs
    Match             *
    region            eu-west-2
    log_group_name    /ecs/sample-api
    log_stream_prefix firelens-
    auto_create_group false

[OUTPUT]
    Name              opensearch
    Match             *
    Host              search-example-domain.eu-west-2.es.amazonaws.com
    Port              443
    TLS               On
    AWS_Auth          On
    AWS_Region        eu-west-2
    Index             ecs-dev-sample-api
    Suppress_Type_Name On
